apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    DB_PASSWORD: AgBAZ15BqkgSPLxaduueXlrXXf0YrR2lw1aXcCITBYLZWCJ4nkL3+TbhTnrcOF+TPg3oRK7pjqr1BpRjGvAdTkNDgGdk9dahMzDtFtqXLhFsSpM0KlrfFNQAhI5atxT93YfEsmvc5+sOV/ehIFQ3CBLZvgCdZa0QhPJqawbdBwuElic+PfAk3Yy22xQutTEUmoxQU3kAdCpRpCzBF8KX/gC2n2A21Ab7hkJZ9aLbGhO7+Yk+LX4ZHBNOkDxQqYXnjwKtG2M5rwTFVh+pm/ZBYMGu4KWUq63PCr14VNh+9poQQ4h0lWRl9vJVE0x+aD2rGJwEhU67jhAG9o6ztDmPn6Hi52nWRSQgmnpcen5U6Ewu1mGRekF+jN4N4A5fSpmEGvF6Y2nnfqhRKn5cUPJeYaU6b/2TDBQ+YUPhJuXyzIMJ73CN6Z/iufnFxdDbt03i3K9Pa+zx5p8qmlKMPKOWylGlS/ni8EwNuK3A4lYFZd5GV6kcQ2/KDqLIgBGtQ/OZgJXjmHqLkNEeyakIQxPx+/JSqiULh71nBmDDQvIwM4W63YYmL0VGmmHSD+QCcDGkJpOxVYBfyl+11ocAifbDSXMbtIhKi+1Wo/xtlUi0/7dkex/FwYwg2bbZ/4e56ydY44uSErklsDIqKSRrcBlLit7AziLHowwGPbqj3o5elA1G7BY6HLJhTbe3nvTXjRHtdpOOYJtpHx0quw==
    DB_USER: AgBFxRTB9q616cnrlEKM/cUFQ73qBIU9fo/sVu0Dt6/xRjqTLZrBmpIjk3vpLqx7AMBkt3ZpPAOYrUoGzmC25UKlCtjFk6yrrtKtG0NHMIPWJy3nPUukFHhVExUWUcNXlVzPy+cw8dByRu7+8s/g338X39coB453pLdGyoTXxjQVWi19wrgGL9fHWw5by42N7ykKUe5DDtvPFP4vM4/j5Y0dqjvzg3osE6yX9Cm/ebp4V2OuujihIGnaooRSVVvzCxUu9KnGTGXJtuAUgTXb4Bb1dJ0GjOLHCdD3CxKE5lQiy33TJ0RqMt7mRp0jdVzA1ql/36Y3YD+fY1R/vw/u9cUjTEoRVQaeDt8gb3aFRhdDFftAO3+iUMetQ22usWwR4zzdNIjYcYIysc3CAyUCkv+6HxWesARxxfUMRrpiJnk6pMl2SptKnrIBoKbJL1fSPD9lHJHzw53KeD5l5rGNPA1wtr2SWstGmaGnSlu3iO9to96bxn8PiAGzXmR9SVrrMapb4hv/tJbz3nqqIoZqeeWSIRVgNIY4uNhVIEVBmJVHxLPHoJ9Bx6pldM1Il3TQLfaqa60T8ADDoshvXt4dLZsT3eemc1k/ttUdWSKZ43ePHr8XILd7O71PgUw9GFWcE5HuMdMn7JhvmsaFaNgPwuUffrrb1LBZ+nrM2RiHkwVMHhaS0UMthut2DPnnUcAdqKg/QahDNpr5MA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: b2bi-prod
    type: Opaque

